### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by MengXin001** [instafluff/Coronavirus#1]
There are some problems in the data of Provinces of China, the data display is incomplete
![report](https://user-images.githubusercontent.com/54111871/76376067-57504c80-6382-11ea-8f1a-41a8a9c55045.png)
maybe the data source has changed

**Comment by instafluff** [comment]
Thank you! You're right, it looks like the data source changed. I've fixed it in 8ac1ed787cd0cc5c640c0c8b7242842ecf33c772 and 25819811de08fbbce3f6d5e0d9d44d747afd7772 now.
